import convokit, textwrap, sys, os
from convokit import Corpus
import scrape

def show_corpus(corpus):
    """
    Display corpus with form as generated by scrape.py using 
    a dfs through utterances.

    Params: corpus (type Corpus)
    """
    pid = None
    for convo in corpus.iter_conversations():
        for utt in convo.traverse('dfs'):
            if utt.meta['type'] == 'comment':
                text = f'{utt.user.id}: \n{utt.text}' # ({utt.meta["permalink"]})'
            else:
                assert utt.meta['type'] == 'submission'
                text = f'{utt.user.id}: !!{utt.meta["title"]}!! {utt.text}' # ({utt.meta["permalink"]})'
            indent(text, utt.meta['depth'], '(r/'+utt.meta['subreddit']+') ')
            if utt.meta['depth'] == 0:
                pid = utt.id
            else:
                try:
                    assert pid == utt.root
                except AssertionError as e:
                    print(f'pid={pid} != utt.root={utt.root}')
                    raise e
    print('--------------------------------------------------')

def indent(text, n=0, label=""):
    print(textwrap.indent(textwrap.fill(text), label + '   ' * n + '| '))
            

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Must specify subreddit name; e.g.:\n\t $ python show_corpus.py coronavirus')
        exit(1)
    else:
        full_path = os.path.join(scrape.base_path, sys.argv[1])
        if not os.path.isdir(full_path):
            print(f'Cannot find corpus at path {full_path} \n\t(path constructed using scrape.base_path)')
            full_path = sys.argv[1]
            if not os.path.isdir(full_path):
                print(f'Also cannot find corpus at path {full_path}')
                exit(1)
            else:
                print(f'Found corpus at path {full_path}')
        else:
            print(f'Found corpus at path {full_path}')
            
        corpus = Corpus(filename=full_path)
        if False:
            corpus.load_info('utterance', scrape.SKIP_FIELDS['utterance'], full_path)
        show_corpus(corpus)
